name: Deployment

on:
  push:
    branches: [master]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Create .env.production for Production
        if: github.ref_name == 'master'
        run: |          
          echo "API_URL=${{ vars.API_URL }}" >> .env.production
          echo "NG_APP_JWT_SECRET=${{ secrets.NG_APP_JWT_SECRET }}" >> .env.production
          
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16.x
          cache: 'bun'

      - name: Install dependencies
        run: bun install

      - name: Run lint
        run: bun lint

      - name: Build project
        run: bun build

      - name: Verify build output
        run: |
          if [ ! -d "dist" ]; then
            echo "Build output directory 'dist' not found!"
            exit 1
          fi



